/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * What this box is waiting on while it is being created
 */

export const BoxProgressPhase = {
    PREPARING_IMAGE: 'preparing_image',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type BoxProgressPhase = typeof BoxProgressPhase[keyof typeof BoxProgressPhase];



