/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BoxProgressPhase } from './box-progress-phase';

export interface BoxProgress {
    /**
     * What this box is waiting on while it is being created
     */
    'phase': BoxProgressPhase;
    /**
     * Suggested wait before asking about this box again, in milliseconds. A hint, not a deadline
     */
    'retryAfterMs': number;
}



