/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ImageUsage {
    /**
     * Images this organization holds. Curated images are the operator’s and are not counted
     */
    'count': number;
    /**
     * How many images this organization may hold
     */
    'limit': number;
    /**
     * Sum of the declared sizes of every pulled version, in bytes. A lower bound on what is stored: it counts what the manifests said, and counts a layer once per version that references it
     */
    'knownBytes': number;
}

