/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ImageVersion {
    /**
     * Version ID
     */
    'id': string;
    /**
     * OCI manifest digest this version was pulled at
     */
    'digest': string;
    /**
     * Sum of the layer sizes the manifest declared, in bytes
     */
    'sizeBytes': number;
    /**
     * The reference the caller asked for, kept verbatim as provenance
     */
    'sourceRef': string;
    /**
     * When this version was first recorded
     */
    'createdAt': string;
}

