/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ImageVersion } from './image-version';

export interface ImageDetail {
    /**
     * What to pass as a box image to boot from this: the curated short name, or the upstream repository path
     */
    'name': string;
    /**
     * Catalog row ID. Null for curated images, which are operator configuration rather than rows
     */
    'id': string | null;
    /**
     * Whether this is one of the operator-provided images every organization shares. Curated images cannot be deleted and do not count against the organization limit
     */
    'curated': boolean;
    /**
     * The exact reference a curated image resolves to. Null for catalog images, which resolve through their versions
     */
    'curatedRef': string | null;
    /**
     * Tags recorded for this image. Empty for curated images, whose reference the operator pins
     */
    'tags': Array<string>;
    /**
     * How many pulled manifest digests this image holds
     */
    'versionCount': number;
    /**
     * Sum of the pulled versions’ declared sizes, in bytes. Layers shared between versions are counted once per version. Null for curated images, whose bytes this system never measured
     */
    'sizeBytes': number | null;
    /**
     * When a box last booted from this image
     */
    'lastUsedAt': string | null;
    /**
     * When this image first entered the catalog. Null for curated images
     */
    'createdAt': string | null;
    /**
     * Every pulled version, newest first
     */
    'versions': Array<ImageVersion>;
    /**
     * Tag movements over time. Always empty today: a tag keeps the digest it first resolved to, so there is nothing to record
     */
    'history': Array<object>;
}

