/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


type ImagesAPI interface {

	/*
	DeleteImage Remove an image from the catalog

	Removes the catalog entry, not the bytes: runners keep whatever they cached, and using the same reference again pulls it back as a new entry. That is also how to pick up a tag that has moved upstream, since a recorded tag keeps the digest it first resolved to.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param idOrRef Catalog ID, or any reference that names the image — URL-encode a reference
	@return ImagesAPIDeleteImageRequest
	*/
	DeleteImage(ctx context.Context, idOrRef string) ImagesAPIDeleteImageRequest

	// DeleteImageExecute executes the request
	DeleteImageExecute(r ImagesAPIDeleteImageRequest) (*http.Response, error)

	/*
	GetImage Get image details

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param idOrRef Catalog ID, or any reference that names the image — URL-encode a reference, since it contains slashes
	@return ImagesAPIGetImageRequest
	*/
	GetImage(ctx context.Context, idOrRef string) ImagesAPIGetImageRequest

	// GetImageExecute executes the request
	//  @return ImageDetail
	GetImageExecute(r ImagesAPIGetImageRequest) (*ImageDetail, *http.Response, error)

	/*
	GetImageUsage Get image usage

	How many images this organization holds against its limit, and the total size its pulled versions declared.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ImagesAPIGetImageUsageRequest
	*/
	GetImageUsage(ctx context.Context) ImagesAPIGetImageUsageRequest

	// GetImageUsageExecute executes the request
	//  @return ImageUsage
	GetImageUsageExecute(r ImagesAPIGetImageUsageRequest) (*ImageUsage, *http.Response, error)

	/*
	ListImages List images

	The organization’s images together with the operator’s curated set, which every organization shares and none can delete.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ImagesAPIListImagesRequest
	*/
	ListImages(ctx context.Context) ImagesAPIListImagesRequest

	// ListImagesExecute executes the request
	//  @return []Image
	ListImagesExecute(r ImagesAPIListImagesRequest) ([]Image, *http.Response, error)
}

// ImagesAPIService ImagesAPI service
type ImagesAPIService service

type ImagesAPIDeleteImageRequest struct {
	ctx context.Context
	ApiService ImagesAPI
	idOrRef string
	xBoxLiteOrganizationID *string
}

// Use with JWT to specify the organization ID
func (r ImagesAPIDeleteImageRequest) XBoxLiteOrganizationID(xBoxLiteOrganizationID string) ImagesAPIDeleteImageRequest {
	r.xBoxLiteOrganizationID = &xBoxLiteOrganizationID
	return r
}

func (r ImagesAPIDeleteImageRequest) Execute() (*http.Response, error) {
	return r.ApiService.DeleteImageExecute(r)
}

/*
DeleteImage Remove an image from the catalog

Removes the catalog entry, not the bytes: runners keep whatever they cached, and using the same reference again pulls it back as a new entry. That is also how to pick up a tag that has moved upstream, since a recorded tag keeps the digest it first resolved to.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param idOrRef Catalog ID, or any reference that names the image — URL-encode a reference
 @return ImagesAPIDeleteImageRequest
*/
func (a *ImagesAPIService) DeleteImage(ctx context.Context, idOrRef string) ImagesAPIDeleteImageRequest {
	return ImagesAPIDeleteImageRequest{
		ApiService: a,
		ctx: ctx,
		idOrRef: idOrRef,
	}
}

// Execute executes the request
func (a *ImagesAPIService) DeleteImageExecute(r ImagesAPIDeleteImageRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ImagesAPIService.DeleteImage")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/images/{idOrRef}"
	localVarPath = strings.Replace(localVarPath, "{"+"idOrRef"+"}", url.PathEscape(parameterValueToString(r.idOrRef, "idOrRef")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xBoxLiteOrganizationID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-BoxLite-Organization-ID", r.xBoxLiteOrganizationID, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ImagesAPIGetImageRequest struct {
	ctx context.Context
	ApiService ImagesAPI
	idOrRef string
	xBoxLiteOrganizationID *string
}

// Use with JWT to specify the organization ID
func (r ImagesAPIGetImageRequest) XBoxLiteOrganizationID(xBoxLiteOrganizationID string) ImagesAPIGetImageRequest {
	r.xBoxLiteOrganizationID = &xBoxLiteOrganizationID
	return r
}

func (r ImagesAPIGetImageRequest) Execute() (*ImageDetail, *http.Response, error) {
	return r.ApiService.GetImageExecute(r)
}

/*
GetImage Get image details

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param idOrRef Catalog ID, or any reference that names the image — URL-encode a reference, since it contains slashes
 @return ImagesAPIGetImageRequest
*/
func (a *ImagesAPIService) GetImage(ctx context.Context, idOrRef string) ImagesAPIGetImageRequest {
	return ImagesAPIGetImageRequest{
		ApiService: a,
		ctx: ctx,
		idOrRef: idOrRef,
	}
}

// Execute executes the request
//  @return ImageDetail
func (a *ImagesAPIService) GetImageExecute(r ImagesAPIGetImageRequest) (*ImageDetail, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ImageDetail
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ImagesAPIService.GetImage")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/images/{idOrRef}"
	localVarPath = strings.Replace(localVarPath, "{"+"idOrRef"+"}", url.PathEscape(parameterValueToString(r.idOrRef, "idOrRef")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xBoxLiteOrganizationID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-BoxLite-Organization-ID", r.xBoxLiteOrganizationID, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ImagesAPIGetImageUsageRequest struct {
	ctx context.Context
	ApiService ImagesAPI
	xBoxLiteOrganizationID *string
}

// Use with JWT to specify the organization ID
func (r ImagesAPIGetImageUsageRequest) XBoxLiteOrganizationID(xBoxLiteOrganizationID string) ImagesAPIGetImageUsageRequest {
	r.xBoxLiteOrganizationID = &xBoxLiteOrganizationID
	return r
}

func (r ImagesAPIGetImageUsageRequest) Execute() (*ImageUsage, *http.Response, error) {
	return r.ApiService.GetImageUsageExecute(r)
}

/*
GetImageUsage Get image usage

How many images this organization holds against its limit, and the total size its pulled versions declared.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ImagesAPIGetImageUsageRequest
*/
func (a *ImagesAPIService) GetImageUsage(ctx context.Context) ImagesAPIGetImageUsageRequest {
	return ImagesAPIGetImageUsageRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return ImageUsage
func (a *ImagesAPIService) GetImageUsageExecute(r ImagesAPIGetImageUsageRequest) (*ImageUsage, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ImageUsage
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ImagesAPIService.GetImageUsage")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/images/usage"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xBoxLiteOrganizationID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-BoxLite-Organization-ID", r.xBoxLiteOrganizationID, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ImagesAPIListImagesRequest struct {
	ctx context.Context
	ApiService ImagesAPI
	xBoxLiteOrganizationID *string
}

// Use with JWT to specify the organization ID
func (r ImagesAPIListImagesRequest) XBoxLiteOrganizationID(xBoxLiteOrganizationID string) ImagesAPIListImagesRequest {
	r.xBoxLiteOrganizationID = &xBoxLiteOrganizationID
	return r
}

func (r ImagesAPIListImagesRequest) Execute() ([]Image, *http.Response, error) {
	return r.ApiService.ListImagesExecute(r)
}

/*
ListImages List images

The organization’s images together with the operator’s curated set, which every organization shares and none can delete.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ImagesAPIListImagesRequest
*/
func (a *ImagesAPIService) ListImages(ctx context.Context) ImagesAPIListImagesRequest {
	return ImagesAPIListImagesRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return []Image
func (a *ImagesAPIService) ListImagesExecute(r ImagesAPIListImagesRequest) ([]Image, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []Image
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ImagesAPIService.ListImages")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/images"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xBoxLiteOrganizationID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-BoxLite-Organization-ID", r.xBoxLiteOrganizationID, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
